[dependencies]
anyhow = "1.0.97"
process_macros = "0.1"
rmp-serde = "1.3.0"
serde_json = "1.0"
uuid = "1.4.1"
wit-bindgen = "0.36.0"

[dependencies.caller-utils]
path = "../target/caller-utils"

[dependencies.hyperprocess_macro]
path = "/Users/zahirsabotic/Documents/Work/hyperprocess-macro/hyperprocess_macro"

[dependencies.hyperware_app_common]
path = "/Users/zahirsabotic/Documents/Work/hyperprocess-macro/hyperware_app_common"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[features]
simulation-mode = []

[lib]
crate-type = ["cdylib"]

[package]
edition = "2021"
name = "todo"
version = "0.1.0"

[package.metadata.component]
package = "hyperware:process"
